[package]
name = "pie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
bigdecimal = "0.3.0"

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
